#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
# and "Hi" at 9th iteration

NUM=1

while [ $NUM -le 10 ]; do
    echo "Holberton School"
    if [ $NUM = 9 ]; then
	echo "Hi"
    fi
    let NUM=$NUM+1
done
