#!/usr/bin/env bash
# This script is displaying the clock to 12:59

HR=0

while [ $HR -le 12 ]; do
    echo "Hour: $HR"
    MN=1
    while [ $MN -le 59 ]; do
	echo $MN
	let MN=$MN+1
    done
    let HR=$HR+1
done
