#!/usr/bin/env bash
# Bash script that changes your home IP
sudo cp /etc/hosts ~/tmphost
sed -i "s/127.0.0.1/127.0.0.2/g" ~/tmphost
echo "8.8.8.8 facebook.com" >> ~/tmphost
sudo cp -f ~/tmphost /etc/hosts
