#!/usr/bin/env bash
# script that configures the container to fit the requirements shorter
pkill -f apache2
sudo chmod 644 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
