#!/usr/bin/env bash
# script that configures the container to fit the requirements shorter
pkill -f apache2
chmod 644 /etc/nginx/nginx.conf
sed -i '1i user nginx;' /etc/nginx/nginx.conf
sed -i 's/80 default/8080 default/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
